### ISSUE TITLE
Constructing instance of WadFile  from Stream instead of FileStream.

### ISSUE THREAD

**Issue by JerryLiew** [LeagueToolkit/LeagueToolkit#273]
Hello, I am currently writing a tool and using the leagueToolKit installed from nuget  to parse wad files, but, i found that the class of WadFile can only construct a instance from FileStream, However , in my project,i used Stream instead of FileStream to read a wadFile. so , i had to downloaded the source code and change the WadFile's Construction parameter to Stream,then i used it in my project,and it works well.(in my project, i only use the WadFile to read all chunks of wadfiles)So I would like to make a suggestion: 
is it possible to change the constrction parameter "FileStream" to "Stream" so that WadFile has the ability of constructing from any Stream?  
thanks a lot.

**Comment by JerryLiew** [comment]
here the WadFile looks like after change the construction parameter.
![image](https://user-images.githubusercontent.com/51161678/236000270-75970890-6ed4-415b-b7e0-69280300a61d.png)

**Comment by Crauzer** [comment]
The reason why `WadFile` only supports `FileStream` is due to the nature of how the file format works. The file is meant to be mounted directly from the filesystem and the implementation requires the knowledge of the Subchunk table entry path.

The Subchunk table is a special entry inside of the file which is needed in order to correctly decompress chunks which use the `ZstdChunked` compression type.
The path of the subchunk entry is the path of the Wad file relative to the Game directory but with a `.subchunktoc` extension. These entries can have partially compressed data which needs to be specially handled by the library.

The only solution I can see here would be to create a new constructor:
```cs
public WadFile(Stream stream, string path);
```
where `path` is the relative path of the Wad file being mounted, but keep in mind that this implementation is still flawed as it would crash if you tried to decompressed a chunk using the `ZstdChunked` compression type

**Comment by Crauzer** [comment]
Here is the relevant code:

https://github.com/LeagueToolkit/LeagueToolkit/blob/24996400aa2de428aa517395ec89775b4b80e3f0/src/LeagueToolkit/Core/Wad/WadFile.cs#LL103C9-L112C79

**Comment by JerryLiew** [comment]
Okay, In that case, it seems better to use the source code and modify the constructors for my special needs, Thank you for your answer.

**Comment by Crauzer** [comment]
I'll close this issue but feel free to make a PR if you find a solution which could work for the library itself
